Update dotnet-docker-build.yml

diff --git a/.github/workflows/dotnet-docker-build.yml b/.github/workflows/dotnet-docker-build.yml
--- a/.github/workflows/dotnet-docker-build.yml
+++ b/.github/workflows/dotnet-docker-build.yml
@@ -50,18 +50,18 @@ jobs:
         run: |
           dotnet format --check --verbosity detailed
 
-      - name: Lint Logs
-        id: lint_status
-        run: |
-          # Lint warnings
-          grep "warning" lint.log | while read -r line; do
-            echo "::warning title=Lint::$line"
-          done || true
-
-          # Lint errors
-          grep "error" lint.log | while read -r line; do
-            echo "::error title=Lint::$line"
-          done || true
+#      - name: Lint Logs
+#        id: lint_status
+#        run: |
+#          # Lint warnings
+#          grep "warning" lint.log | while read -r line; do
+#            echo "::warning title=Lint::$line"
+#          done || true
+#
+#          # Lint errors
+#          grep "error" lint.log | while read -r line; do
+#            echo "::error title=Lint::$line"
+#          done || true
 
       ### TEST ANNOTATIONS ###
 #      - name: Run Tests and Save Results
